# Generated by Django 3.2.7 on 2023-10-26 00:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country')),
                ('state', models.CharField(default='Texas', max_length=180)),
                ('account_number', models.IntegerField(default=9118872201)),
                ('account_type', models.CharField(default='E Checking', max_length=180)),
                ('opening_date', models.CharField(default='4/6/2000', max_length=180)),
                ('opening_amount', models.FloatField(default=4800000.0)),
                ('present_amount', models.FloatField(default=97000000.0)),
                ('next_of_kin', models.CharField(default='Monika A. Hinks', max_length=200)),
                ('maiden_name', models.CharField(default='Sylvester', max_length=200)),
                ('pet_name', models.CharField(default='Jack', max_length=200)),
                ('favorite_color', models.CharField(default='white', max_length=200)),
            ],
        ),
    ]
